[libraries]
koin-android = "io.insert-koin:koin-android:3.2.1"
koin-core = "io.insert-koin:koin-core:3.2.1"
koin-android-compose = "io.insert-koin:koin-androidx-compose:3.2.1"
apache-commons-codec = "commons-codec:commons-codec:1.15"
